LEAVES_WEB_URL=https://qrisp.eastus.cloudapp.azure.com
LEAVES_API_URL=https://qrisp.eastus.cloudapp.azure.com
LEAVES_API_TOKEN=NTVkYmQyMTE1N2EyOGZjODg4Yzk1ZDg5OTYxN2Y1MGMxYjJhOTA4NWVjMjRjMTc0YWY1YjAyZDcxMWU0YmE1Zg
MYSQL_ROOT_PASSWORD=wallaroot
SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
SYMFONY__ENV__DATABASE_HOST=db
SYMFONY__ENV__DATABASE_PORT=3306
SYMFONY__ENV__DATABASE_NAME=wallabag
SYMFONY__ENV__DATABASE_USER=wallabag
SYMFONY__ENV__DATABASE_PASSWORD=wallapass
SYMFONY__ENV__MAILER_HOST=127.0.0.1
SYMFONY__ENV__MAILER_USER=~
SYMFONY__ENV__MAILER_PASSWORD=~
SYMFONY__ENV__FROM_EMAIL=rahul.singh@anant.us
