LEAVES_WEB_URL=https://qrisp.eastus.cloudapp.azure.com
LEAVES_API_URL=https://qrisp.eastus.cloudapp.azure.com
LEAVES_API_TOKEN=NTVkYmQyMTE1N2EyOGZjODg4Yzk1ZDg5OTYxN2Y1MGMxYjJhOTA4NWVjMjRjMTc0YWY1YjAyZDcxMWU0YmE1Zg